# Generated by Django 4.2.3 on 2023-07-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('codigo_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('desarrollo', 'Desarrollo'), ('diseno', 'Diseño'), ('ventas', 'Ventas')], default='desarrollo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('iden', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url', models.URLField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('nombre_corto', models.CharField(max_length=30, unique=True)),
                ('duenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Juguete_Mascota',
            fields=[
                ('iden', models.IntegerField(primary_key=True, serialize=False)),
                ('juguete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.juguete')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
