# Generated by Django 4.2.3 on 2023-07-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juguete',
            name='iden',
        ),
        migrations.RemoveField(
            model_name='juguete_mascota',
            name='iden',
        ),
        migrations.AddField(
            model_name='juguete',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juguete_mascota',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juguete_mascota',
            name='juguete',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='mascotas.juguete'),
        ),
    ]
