# Generated by Django 4.2.3 on 2023-07-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_remove_juguete_iden_remove_juguete_mascota_iden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete_mascota',
            name='juguete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.juguete'),
        ),
    ]
